services:
  web:
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
      redis:  
        condition: service_healthy
    build: .
  postgres:
    env_file:
        - .env
    image: postgres:16-alpine
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - postgresVolume:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - redisVolume:/data/redis
volumes:
  postgresVolume:
  redisVolume: